### ISSUE TITLE
[BUG] Fray damage not included in Harm

### ISSUE THREAD

**Issue by Drills** [whitespine/foundryvtt-icon#13]
I noticed that Fray damage is not being included in the harm `Roll` option.
I did a little digging and found that `@class.fray_damage` is being evaluated as 0.

Foundry `Version 11 Stable, Build 313`, `ICON System 0.3.23`

[Line where I think the issue is](https://github.com/whitespine/foundryvtt-icon/blob/5a3fa6adb2199fbffce968237af570017d03cc9b/src/view/apps/DamageRollPromptShell.svelte#L46)

**Comment by whitespine** [comment]
Good catch. Resolved in new version 0.3.24
