### ISSUE TITLE
[BUG] Harm tool doesn't display properly, nor does it apply damage when clicked

### ISSUE THREAD

**Issue by eldritchkermit** [whitespine/foundryvtt-icon#14]
**Module Version:** v0.3.24

**Describe the bug**
When I open the Harm tool from the toolbar, it displays only halfway through the lower portion of the screen, thus making several of its options unavailable for clicking. Additionally, when I select a token and select one of the few clickable options, it does not apply damage to them. I have tried disabling any non-mandatory modules, but nothing changed.

**To Reproduce**
1. Click on the "Harm" tool on the toolbar, which shows up in the way described above and in the screenshot in this Issue
2. Click on the token you wish to apply damage to, which will highlight it and cause it to show up in the Harm tool's portrait
3. Click on any of the damage buttons, but no damage will be applied

**Expected behavior**
The Harm tool's interface should fully show up, and apply damage to the selected token when clicking on the respective options.

**Screenshots**
![image_2023-11-24_154904983](https://github.com/whitespine/foundryvtt-icon/assets/91407094/1769120e-c957-4816-8ea1-c63b1a7351c8)

**Foundry Version:** 
v11 (315)

**Game System:** 
ICON System

**Comment by whitespine** [comment]
What dimensions is your browser running in?

Additionally, could you please verify you are using T (or whatever method you prefer) to _target_ the token? Selecting isn't how you apply damage.

**Comment by eldritchkermit** [comment]
I am running the desktop version of Foundry, I am not sure how to check the dimensions for it

Alright, the targeting works, that was my bad, sorry

**Comment by eldritchkermit** [comment]
The only remaining issue is the crop, which I am not really sure how to check, since I am using the desktop version of Foundry

**Comment by whitespine** [comment]
I am having difficulty actually getting the desktop client to work at all for me, unfortunately. Does the issue persist if you connect via browser locally? Might be a temporary workaround until I can replicate.

**Comment by eldritchkermit** [comment]
The issue still persists, even on a browser

**Comment by whitespine** [comment]
Interesting. Might make it easier to solve honestly.

What browser/OS? Are you zoomed in at all or using any modules that might influence styling/theming? Do you utilize any OS or browser wide settings to change font size?

Thanks.

**Comment by whitespine** [comment]
Misclick on the phone ui

**Comment by eldritchkermit** [comment]
> Interesting. Might make it easier to solve honestly.
> 
> What browser/OS? Are you zoomed in at all or using any modules that might influence styling/theming? Do you utilize any OS or browser wide settings to change font size?
> 
> Thanks.

The browser is Opera GX, the OS is Windows 10, I am not zooming in nor using any modules that might influece styling or theming, nor have I applied any changes to the font size, nor have any of the other people in my group who have the same issue

**Comment by whitespine** [comment]
I was totally unable to reproduce. However, from the screenshot it just seems like it sometimes needs a bit more width, so I made it wider. v0.3.25 should work, hopefully. Please let me know
