### ISSUE TITLE
[BUG] Wounds affecting max hp value leads to readability issues and problems with the damage planner

### ISSUE THREAD

**Issue by Rats808** [whitespine/foundryvtt-icon#19]
**Module Version:** v0.3.27

**Describe the bug**
When adding wounds to an actor, while using a health bar(in my case with Bar Brawl, but I believe it would still be an issue with the standard resource bars), 50% of a character's HP becomes harder to gauge. With 0 Wounds, it's easy to tell someone is Bloodied when their hp hits the half-way mark, or 50% if you have a percentage label:
![image](https://github.com/whitespine/foundryvtt-icon/assets/13080757/6ac82a77-c347-42b8-acfb-74806882cdb6)
However, with 1 wound, and the same amount of hp, that mark is changed instead to 67%(this token has the same amount of hp, but due to the lowered max hp, it reads as higher):
![image](https://github.com/whitespine/foundryvtt-icon/assets/13080757/bdc2de10-0d47-4ca0-b12c-15734fdf519c)
This is mainly an issue from the GM perspective, since foes are unlikely to have Wounds and you can tell from your own sheet when you're Bloodied. The GM however has to open a sheet to check if a PC is Bloodied, unless they memorize each PCs current Wounds.

Additionally, the Damage Planner evidently uses the token/actor's max hp affected by wounds to determine what 25% hp damage is(the correct value is 8; the second line is after adding a wound which causes it to treat 25% of 32 hp as 6):
![image](https://github.com/whitespine/foundryvtt-icon/assets/13080757/599c9a54-a551-43ba-bd78-600a6bd47f79)

**To Reproduce**
1. Create a character, drag their token onto the canvas
2. Set up a resource bar to track their hp, and display a percentage
3. Set their hp to 50% of their max(14 for Vagabonds, 16 for Wrights, 20 for Stalwarts and Mendicants)
4. Add a wound; the percentage displayed by the bar will jump up to a value around 67%, making it harder to judge at a glance that the PC is Bloodied

**Expected behavior**
I would appreciate it if it were easier to judge at a glance whether or not a PC is Bloodied. Having something closer to the example HP bar in the book's example(pg 82 of Icon 1.5) would be nice, but I'm aware that getting Wounds and Vigor to display like that requires Bar Brawl, and that module is not currently marked as a dependency for this system/not everyone will necessarily want to use it.
Additionally, the Damage Planner's 25% button should give the same amount of damage regardless of the number of wounds the character has.

**Comment by whitespine** [comment]
I've tweaked this behavior for the next release. Max hp will remain constant.
There is now a new field on players (system.eff_max_hp) that tracks the old reduced value.
